[package]
name = "apolysis-daemon"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
apolysis-accountability = { path = "../apolysis-accountability" }
apolysis-core = { path = "../apolysis-core" }
apolysis-kubernetes = { path = "../apolysis-kubernetes" }
apolysis-kubernetes-source = { path = "../apolysis-kubernetes-source" }
apolysis-observer = { path = "../apolysis-observer" }
apolysis-store = { path = "../apolysis-store" }
libc.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio = { workspace = true, features = [
    "io-util",
    "macros",
    "net",
    "process",
    "rt-multi-thread",
    "signal",
    "sync",
    "time",
] }

[[bin]]
name = "apolysisd"
path = "src/main.rs"

[[bin]]
name = "apolysisd-health"
path = "src/bin/apolysisd-health.rs"

[[bin]]
name = "apolysisd-control"
path = "src/bin/apolysisd-control.rs"
